# Generated by Django 3.0.2 on 2020-02-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escalation',
            name='type',
            field=models.CharField(choices=[('clarification', 'calrification'), ('Request', 'Request'), ('Other', 'Other'), ('Question', 'Question')], max_length=20),
        ),
    ]
