# Generated by Django 3.0.2 on 2020-02-12 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_auto_20200212_0843'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawfeedback',
            name='object_of_concern',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
