# Generated by Django 3.0.2 on 2020-01-21 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='permits',
        ),
        migrations.AddField(
            model_name='seller',
            name='trade_license',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='SellerPermits',
        ),
    ]
