# Generated by Django 3.0.2 on 2020-01-21 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_buyer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='location',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='profile_picture',
        ),
        migrations.DeleteModel(
            name='SellerEmployee',
        ),
    ]
