# Generated by Django 3.0.2 on 2020-01-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_selleremployee'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Seller',
            new_name='SellerFactory',
        ),
    ]
