# Generated by Django 3.0.2 on 2020-01-22 03:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20200121_1856'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SellerEmployee',
            new_name='SellerFactoryEmployee',
        ),
    ]
