# Generated by Django 3.0.2 on 2020-01-22 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20200122_0303'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerfactory',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
