# Generated by Django 3.0.2 on 2020-01-27 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sellerfactory_factory_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerfactory',
            name='date_created',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
