# Generated by Django 3.0.2 on 2020-01-30 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_sellerfactory_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerfactory',
            name='googlemap',
            field=models.TextField(null=True),
        ),
    ]
