# Generated by Django 3.0.2 on 2020-02-14 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_sellerfactory_googlemap'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerfactory',
            name='factory_bio',
            field=models.TextField(default='No bio'),
        ),
    ]
