# Generated by Django 3.0.3 on 2020-02-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20200225_1411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='profile_picture',
            new_name='profile_photo',
        ),
        migrations.AddField(
            model_name='buyer',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buyer',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='use_case',
            field=models.TextField(null=True),
        ),
    ]
