# Generated by Django 3.0.3 on 2020-02-25 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_auto_20200225_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='buyer',
            old_name='profile_photo',
            new_name='profile_picture',
        ),
    ]
