# Generated by Django 3.0.2 on 2020-01-22 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_sellerfactory_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tonnes', models.IntegerField()),
                ('price_per_tonne', models.IntegerField()),
                ('date_harvested', models.DateField()),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.SellerFactoryEmployee')),
                ('factory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.SellerFactory')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField()),
                ('price', models.IntegerField()),
                ('shipping_address', models.TextField()),
                ('shipment_id', models.TextField()),
                ('auction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='transactions.Auction')),
                ('buyer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Buyer')),
            ],
        ),
    ]
