# Generated by Django 3.0.2 on 2020-01-24 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_sellerfactory_factory_logo'),
        ('transactions', '0002_auto_20200123_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.SellerFactoryEmployee'),
        ),
    ]
