# Generated by Django 3.0.2 on 2020-01-24 04:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_auto_20200124_0444'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='order',
            name='expected_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='auction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.Auction'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipment_id',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.TextField(default='awaiting confirmation'),
        ),
    ]
