# Generated by Django 3.0.2 on 2020-01-24 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0007_auto_20200124_0522'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_placed',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
