# Generated by Django 3.0.2 on 2020-01-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_auto_20200124_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='date_placed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
