# Generated by Django 3.0.2 on 2020-01-28 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0012_auto_20200127_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='tonnes_left',
            field=models.IntegerField(null=True),
        ),
    ]
