# Generated by Django 3.0.2 on 2020-01-29 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_auction_tonnes_left'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='user',
            new_name='sender',
        ),
    ]
