# Generated by Django 3.0.2 on 2020-01-30 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_auto_20200130_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='datetime',
            field=models.DateTimeField(),
        ),
    ]
