# Generated by Django 3.0.2 on 2020-01-30 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0016_auto_20200130_1641'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='datetime',
        ),
        migrations.AddField(
            model_name='chat',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
