# Generated by Django 3.0.2 on 2020-02-01 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0019_order_chain_valid'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_hash',
            field=models.CharField(default='', max_length=200),
        ),
    ]
