# Generated by Django 3.0.2 on 2020-02-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_order_order_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bean_size',
            field=models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], default='small', max_length=20),
        ),
        migrations.AddField(
            model_name='auction',
            name='coffee_type',
            field=models.CharField(choices=[('Arabica', 'Arabica'), ('Robusta', 'Robusta')], default='Arabica', max_length=10),
        ),
        migrations.AddField(
            model_name='auction',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='auction',
            name='humidity',
            field=models.TextField(default='Not Provided', max_length=12),
        ),
        migrations.AddField(
            model_name='auction',
            name='soil_ph',
            field=models.TextField(default='Not Provided', max_length=12),
        ),
        migrations.AddField(
            model_name='auction',
            name='status',
            field=models.CharField(choices=[('Washed', 'Washed'), ('semi-washed', 'semi-washed'), ('honey', 'honey'), ('natural', 'natural')], default='Washed', max_length=20),
        ),
        migrations.AddField(
            model_name='auction',
            name='tempreture',
            field=models.CharField(default='Not Provided', max_length=12),
        ),
    ]
