# Generated by Django 3.0.2 on 2020-02-02 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0022_auto_20200201_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
