# Generated by Django 3.0.2 on 2020-02-02 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0023_auction_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_time_on_ship',
            field=models.CharField(default='0', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_company',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shipment_handler_phone',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='order',
            name='time_of_shipping',
            field=models.DateTimeField(default='2020-02-01'),
        ),
        migrations.AddField(
            model_name='order',
            name='vessel_number',
            field=models.CharField(default='', max_length=20),
        ),
    ]
