# Generated by Django 3.0.2 on 2020-02-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0024_auto_20200202_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipment_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
