# Generated by Django 3.0.2 on 2020-02-02 12:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_auto_20200202_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='time_of_shipping',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
    ]
