# Generated by Django 3.0.2 on 2020-02-07 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0029_auto_20200202_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='arrived',
            field=models.BooleanField(default=False),
        ),
    ]
