# Generated by Django 3.0.2 on 2020-02-17 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0032_auto_20200217_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='employee',
        ),
    ]
