# Generated by Django 3.0.2 on 2020-02-19 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0036_auto_20200219_0556'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='sold_out',
            field=models.BooleanField(default=False),
        ),
    ]
