# Generated by Django 3.0.2 on 2020-02-19 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_sellerfactory_factory_bio'),
        ('transactions', '0039_auto_20200219_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='employee',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.SellerFactoryEmployee'),
        ),
    ]
