# Generated by Django 3.0.2 on 2020-02-23 16:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0040_auto_20200219_0732'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='when_arrived',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
