# Generated by Django 3.0.3 on 2020-03-01 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0041_order_when_arrived'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='grade',
            field=models.TextField(choices=[('Grade 1', 'Grade 1'), ('Grade 2', 'Grade 2'), ('Grade 3', 'Grade 3')], default='Grade 1', max_length=20),
        ),
        migrations.AlterField(
            model_name='auction',
            name='humidity',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='auction',
            name='soil_ph',
            field=models.CharField(default='0', max_length=12),
        ),
        migrations.AlterField(
            model_name='auction',
            name='tempreture',
            field=models.CharField(default='0', max_length=12),
        ),
    ]
