# Generated by Django 3.0.2 on 2020-02-15 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0015_sellerfactory_factory_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackAuction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tonnes', models.IntegerField()),
                ('tonnes_left', models.IntegerField(null=True)),
                ('price_per_tonne', models.IntegerField()),
                ('date_harvested', models.DateField()),
                ('bean_size', models.CharField(choices=[('small', 'small'), ('medium', 'medium'), ('large', 'large')], default='small', max_length=20)),
                ('status', models.CharField(choices=[('Washed', 'Washed'), ('semi-washed', 'semi-washed'), ('honey', 'honey'), ('natural', 'natural')], default='Washed', max_length=20)),
                ('tempreture', models.CharField(default='Not Provided', max_length=12)),
                ('description', models.TextField(default='')),
                ('humidity', models.CharField(default='Not Provided', max_length=12)),
                ('soil_ph', models.CharField(default='Not Provided', max_length=12)),
                ('coffee_type', models.CharField(choices=[('Arabica', 'Arabica'), ('Robusta', 'Robusta')], default='Arabica', max_length=10)),
                ('date_placed', models.DateTimeField(auto_now_add=True, null=True)),
                ('verified', models.BooleanField(default=False)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.SellerFactoryEmployee')),
                ('factory', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.SellerFactory')),
            ],
        ),
        migrations.CreateModel(
            name='BackOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_placed', models.DateField(auto_now_add=True, null=True)),
                ('expected_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.IntegerField()),
                ('status', models.IntegerField(default=0)),
                ('shipping_address', models.TextField(blank=True, null=True)),
                ('shipment_id', models.CharField(blank=True, max_length=20, null=True)),
                ('vessel_number', models.CharField(default='', max_length=20)),
                ('shipment_company', models.CharField(default='', max_length=20)),
                ('estimated_time_on_ship', models.CharField(default='0', max_length=20)),
                ('time_of_shipping', models.DateField(default='2020-01-01')),
                ('shipment_handler_phone', models.CharField(default='', max_length=15)),
                ('arrived', models.BooleanField(default=False)),
                ('chain', models.TextField(default='')),
                ('chain_valid', models.BooleanField(default=False)),
                ('order_hash', models.CharField(default='', max_length=200)),
                ('auction', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backup.BackAuction')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.Buyer')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.SellerFactoryEmployee')),
            ],
        ),
        migrations.CreateModel(
            name='BackChat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='backup.BackOrder')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
