# Generated by Django 3.0.2 on 2020-02-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backorder',
            name='date_placed',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
