# Generated by Django 3.0.2 on 2020-02-19 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_sellerfactory_factory_bio'),
        ('backup', '0003_auto_20200217_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backauction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.SellerFactoryEmployee'),
        ),
        migrations.AlterField(
            model_name='backauction',
            name='factory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.SellerFactory'),
        ),
    ]
