# Generated by Django 3.0.2 on 2020-02-19 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0004_auto_20200219_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='backauction',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
