# Generated by Django 3.0.3 on 2020-02-28 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backup', '0005_backauction_parent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='backorder',
            name='parent_id',
            field=models.IntegerField(default=0),
        ),
    ]
